### ISSUE TITLE
Failing to understand hook call

### ISSUE THREAD

**Issue by md1023** [altsol/hg-mattermosthooks#3]
Typical in-process hook is written this way: `check(ui, repo, hooktype, node=None, source=None, **kwargs)`, according to examples here https://www.mercurial-scm.org/wiki/HookExamples. I am accustomed to this example in my hooks.

Please explain how does your approach work:
`pushhook(node, hooktype, url, repo, source, ui, **kwargs):`

As you can see, arguments arranged otherwise. What do I miss?

My original question is similar to #2, but we use ssh and still get root@server.server as an author of changegroup. I thought this information could be in hook arguments, but I don't understand them in your case.

**Comment by thanosk** [comment]
Mercurial documentation on this matter is vague and outdated. Your best bet for documentation is to look around at other hooks and stuff in mercurial's source code hgext/ and tests/ directories (probably contrib/ as well). Apparently, the arrangement of the arguments doesn't seem to matter, instead the naming of the arguments does.

In any way, since you seem to be able to play around with the code, you can try re-arranging the arguments if it feels more natural and hooking some debugging code in there to check what the arguments contain. Don't forget that this project was originally forked from a hg hook for Slack, so most things are deliberately not re-arranged for keeping a thin backwards compatibility line. By the way, can you also check on https://github.com/oblalex/hg-slackhooks/issues/1 ? Perhaps it can clarify things a bit more.

To get to the bottom line of the problem behind issue #2, in a remote-server push situation, don't forget that there are user accounts involved both locally and remotely. HG runs on your PC as your user, but it also runs on the remote server probably using a different user (root in your case, www-data in other cases, etc). If you install the post-push hook (aka changegroup) on the remote server, the remote's server user is going to show up in your notifications, no matter what. You could grab the real author from inside the changesets object, but this solution would also have a couple of issues. One of them is described in issue #2 (you can never know the real pusher, only who commited, in case your organization uses a different person as Source Code Manager (merger)), and secondly, we would definitely loose the grouping feature (as in user blah blah pushes these 5 changesets).

Does the above help?

**Comment by md1023** [comment]
Well, arguments just work :)

From Mercurial IRC:
[15:02] \<md1023\> Can I get ui.username on a remote machine from his machine's hgrc config during push hook? Or it is not supplied in incoming changesets?
[15:20] \<av6\> md1023: if i understand correctly, you want pusher's username? that's not possible, because pushes aren't logged in mercurial
[15:20] \<av6\> only if you set up some auth you can see pusher's identity
[15:21] \<md1023\> thanks, i can use ssh auth user maybe
[15:21] \<av6\> there's contrib/hg-ssh for setting up hg-only ssh access
